name = "challenge"
type = "javascript"

# workers dx
account_id = "<< ACCOUNT ID >>"
workers_dev = true
zone_id = ""
route = ""

[build]
command = "yarn build"
watch_dir = "worker"

[build.upload]
format = "service-worker"

# [secrets]
# SPARKPOST_KEY

[[kv_namespaces]]
binding = "DATA"
preview_id = "<< KV NAMESPACE ID >>"
id = "<< KV NAMESPACE ID >>"
