name = "challenge"
type = "javascript"

# workers dx
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
workers_dev = true
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "challenge.developers.cloudflare.com/*"

[build]
command = "yarn build"
watch_dir = "worker"

[build.upload]
format = "service-worker"

# [secrets]
# SPARKPOST_KEY

[[kv_namespaces]]
binding = "DATA"
preview_id = "9b39e1c1e9fa47a0a387923fa395fac8"
id = "9b39e1c1e9fa47a0a387923fa395fac8"
